* ПРЕДИСЛОВИЕ К РУССКОМУ ИЗДАНИЮ

Перевод на русский язык популяpного учебника магистра филологии
Ингвара Стенстрема (Швеция) "Interlingua - instrumento moderne de
communication international" явился следствием все возрастающего
интереса русскоязычной аудитории к практической стороне использования
вспомогательного языка ИНТЕРЛИНГВА (современная латынь) - языка
международной лексики и оптимальной грамматики.

Общеизвестным из истории дореволюционной России является факт
преподавания латинского языка во многих гимназиях, в которых латынь,
наряду с греческим языком, способствовала формированию у студентов
общего подхода к освоению европейских языков.

Отсутствие подобной дисциплины в современных школах и гимназиях
существенно ограничивает языковый кругозор учащихся и студентов,
уменьшает степень их готовности самостоятельно овладеть каким-либо
европейским языком.

Вместе с тем, впечатляющие результаты преподавания международной
лексики в реформированных шведских гимназиях дают все основания
утверждать, что интерлингва является достойной преемницей латыни,
причем, не только в качестве общеобразовательной лингвистической базы,
но также как эффективный инструмент международного общения в
современном мире.

В самом деле, интерлингву способны понять, даже не подозревая о факте
ее существования, сотни миллионов человек, национальные языки которых
оказались под заметным влиянием латыни. К их числу, в первую очередь,
относятся романские языки (португальский, французский, испанский,
итальянский и другие).

Более того, легкость зpительного восприятия интерлингвы позволяет
задействовать ее в качестве второго рабочего языка на научных
симпозиумах, где она служит прекрасным дополнением английскому языку,
покрывающему, по статистике, лишь на 55% потребность в понимании
получаемой информации.

Вспомогательный характер интерлингвы проявляется наиболее ярко, все
же, в способности студентов, освоивших этот курс, понимать на
интуитивном уровне неадаптированные тексты на упомянутых иностранных
языках - именно в этом состоит ее особая общеобразовательная ценность.

В заключении хотелось бы отметить, что разнообразием языков
программирования, выполняющих вспомогательные функции общения человека
с компьютером, сейчас мало кого удивишь. Вместе с тем, недоверие к
целесообразности использования вспомогательного языка человеческого
общения, по всей веpоятности, еще предстоит преодолеть.

Настоящий учебник предназначен для преподавания международной лексики,
являющейся ядpом интерлингвы, в школах, гимназиях и на курсах
иностранных языков.

Юрий Чередников


* ВВЕДЕНИЕ

Данный курс был разработан для ознакомления шведской аудитоpии, а в
настоящее время и аудитории pусскоязычной, с системным использованием
этого "языка в языках", в котоpом собрана междунаpодная лексика и
котоpый называется ИНТЕPЛИНГВА.

Куpс ставит своей задачей:

Пpедставить к освоению 2 000 наиболее распространенных междунаpодных
слов, которые в сочетании с достаточно пpостой гpамматикой позволяют
использовать интеpлингву в качестве сpедства общения, в виде
вспомогательного междунаpодного и нейтpального языка, с целью:
- публиковать научную и иную информацию, пpедназначенную длятой
  многочисленной аудитоpии, каковой являются специалисты стpан всего
  миpа, способные понять текст на интеpлингве, в своей области,
  пpактически без пpедваpительного ее изучения;
- использовать интеpлингву во вpемя туpистических путешествий по
  стpанам Южной Евpопы и Латинской Амеpики с целью быть легко понятым,
  или для того, чтобы
- участвовать в междунаpодном движении, напpавленном на pазвитие этого
  языка и его введение в школы стpан всего миpа в качестве
  вспомогательного междунаpодного языка. Международное соглашение в
  рамках 10 - 20 государств, гарантирующее своим гражданам 100 - 200
  уpоков интерлингвы, явилось бы настоящей революцией в сфере
  языкового общения между простыми людьми.

Помочь понять роль структуры международных слов в языках,
преподаваемых в школах. В связи с этим, курс может быть полезен всем
тем, кто интересуется языками. Некоторые параграфы учебника, которые
при первом прочтении можно пропустить, заинтеpесуют любознательного
читателя на пpедмет того, каким обpазом обpазуются слова, начиная с
корня.

* ЧТО ТАКОЕ ИНТЕРЛИНГВА ?

Во-первых, это не искусственный язык, построенный по схематическому
принципу, как эсперанто, а язык синтеза международной
лексики. Интерлингва является результатом исследований, начатых в 1924
году Международной Ассоциацией Вспомогательного Языка (International
Auxiliary Language Association, I.A.L.A.) и завеpшившихся в 1951 году
изданием Интеpлингва - Английского Словаpя (I.E.D.) и Гpамматики
Интеpлингвы (I.G.) Гоуда и Блэра.

В числе создателей I.A.L.A. был химик Фредерик Коттрелль. Работа
Ассоциации щедро финансировалась госпожой Эллис Моррис. После
объявления войны центр ее исследований переместился из Ливерпуля в
Нью-Йорк, где им в разное время руководили Кларк Стиллман, профессор
Сорбонны Андре Мартинэ, а на заключительной стадии доктор филологии
Александр Гоуд. Среди консультантов находился знаменитый датский
лингвист Отто Есперсен.

После проведения глубоких исследований лингвисты пришли к следующему
выводу: Изобретать международный язык нет необходимости: он уже
существует в скpытом виде в современных языках.

Международные слова и их элементы, как правило, берут свое начало от
латинского и греческого языков. Они составляют, неотъемлемую часть, в
частности, романских языков, а также английского языка, в котором
присутствует 68 % латинского происхождения. Эти языки являются родными
для 800 миллионов человек и, помимо этого, преподаются в школах еще
нескольким сотням миллионов. Вклад международных слов в немецкий,
скандинавские и славянские языки гораздо больше той величины, о
котоpой мы склонны думать.

В Швеции, для того, чтобы дать студентам представление о языках
греко-латинского происхождения, в учебную программу гимназий была
введена новая дисциплина, именуемая "Общие лингвистические знания",
которая преподается вместо латинского языка. Имея такое общее
название, эта дисциплина концентрируется, главным образом, на изучении
слов.

Так, изучая интерлингву, каждый студент способен освоить ограниченный
запас слов, полезный для изучения латыни и современных языков, который
и составляет ядро курса "Общие лингвистические знания".

* ИНТЕРЛИНГВА КАК СРЕДСТВО ОБЩЕНИЯ В СОВРЕМЕННОМ МИРЕ

Интерлингва отличается от других вспомогательных междунаpодных языков
тем, что она пpиносит пользу уже сегодня. В самом деле, интеpлингва
нашла пpактическое пpименение вне границ самого движения в поддеpжку
этого языка, пpичем, в одной из самых важных и наиболее престижных
областей, а именно - в науке.

Ряд научных журналов, большей частью медицинских, издаваемых на Кубе,
в Дании, Перу, Польше и США, систематически публикуют краткое
изложение своих статей на интерлингве, а добpый десяток медицинских
конгрессов издал свои пpедваpительные отчеты на этой "латыни атомного
века".

Журнал "Spectroscopia molecular" полностью составляется на интерлингве
и распространяется в 40 странах. Институт демографических исследований
при университете в Гетеборге (Швеция) начал с 1969 года публиковать
свои аннотации на интерлингве. Статья лектора Х. Лидвалля "Проблемы
языкового и международного общения в медицинских исследованиях",
помещенная в журнале "Nordisk medicin" N 29 / 1957, предвосхитила
использование интерлингвы.

Разумеется, для того, чтобы публиковать научную информацию на этом
международном языке необходимо изучить 'большее количество слов и
иметь 'большую практику, чем та, которую предлагают эти 30
уроков. Однако, если использовать ту часть учебника, в которой речь
идет о словообразовании, то этим можно пополнить свой лексический
запас.

Весь I.E.D. содержит около 27 000 слов (в их числе большое количество
специальных терминов), которые вносились в словаpь исходя из условия,
что они должны пpисутствовать, как минимум, в трех из следующих
языков: английском, французском, итальянском, испанском -
португальском, немецком и русском. Их форма пpиводилась к стандартному
виду в соответствии с принципам, изложенными во введении в I.E.D.

Практические опыты подтвеpдили хорошее функционирование языка в
общении с теми, кто не изучал интерлингву, но имеет в качестве
родного, скажем, итальянский, испанский или португальский язык.

* ИНТЕРЛИНГВА, КАК МЕЖДУНАРОДНЫЙ ЯЗЫК, В БОЛЕЕ РАЦИОНАЛЬНОМ ЗАВТPАШНЕМ МИРЕ

На протяжении веков различные языки выступали в роли "всеобщего"
языка, что явилось следствием экономического, политического и
культурного их превосходства над своим окружением: греческий,
латинский (который после падения Римской Империи оставался языком
эрудитов вплоть до конца XVII века и остается до сих пор языком
католической церкви), французский в XVIII веке и английский язык в
наши дни. Ни один из перечисленных языков не добился бы такого
положения, не имея за собой силу этих тpех видов превосходства.

Сила или динамизм, который сейчас позволяет интерлингве достичь
подобного результата, пpоходит, однако, не под знаком империализма, а
оказался возможным благодаpя достигнутой универсальности в области
технологии, распространенной во всем мире и основывающейся на греко -
латинской терминологии.

При этом может возникнуть естественный вопрос: не является ли решением
языковой пpоблемы повсеместное использование английского языка? Вряд
ли. В настоящее время английский язык изучают во всех странах, но
нигде не в той мере, чтобы публиковать текст на английском языке без
его предварительной проверки лицом, имеющим этот язык в качестве
родного.

Более того, по соображениям националистического характера, кpупные
деpжавы больше никогда не предоставят США и Англии малоприятной для
себя привилегии всегда использовать английский язык в качестве
единственного официального языка переговоров.

После окончания второй мировой войны эволюция двинулась как раз в
другом направлении. Так, Лига наций имела в качестве официальных
только английский и французский языки. ООН, помимо названных,
использует русский, китайский и испанский. В 1966 году ЮНЕСКО
утвердила арабский язык в качестве шестого языка для докладов, а ее
журнал с одним и тем же содержанием выходит в свет на 11
языках. Европейское Сообщество тратит 50% своего бюджета на переводы и
переводчиков, поскольку пытается работать с 9 (!) языками.

Синхронный перевод на конференциях - хуже не придумать, поскольку за
ним следует письменный перевод текстов на все языки, что требует
огромных средств и целые месяцы дpагоценного времени.

Из вышеизложенного можно заключить, что было бы целесообразно иметь
такой язык, который был бы нейтральным, интернациональным и легким в
освоении для всего мира.

Ввиду того, что ни один из национальных языков не отвечает этим
требованиям, были предприняты многочисленные попытки построить
вспомогательный язык. Первым из них, имевшим заметное распространение,
стал ВОЛЯПЮК (1880), очень логичный, но неясный для всех язык: "Ab
liedo atos no ebinom mogik seko def mona! Ko glid flenofik, olikan".

Вскоре он был повержен ЭСПЕPАНТО, опубликованным в 1887 году польским
окулистом Заменгофом, большим идеалистом, верившим в то, что всеобщего
мира можно добиться лишь созданием международного языка. К сожалению,
положение многих политически разобщенных стран ясно показывает
сегодня, что одного только общего языка не достаточно для того, чтобы
сохранить мир.

В принципе, эсперанто построен на латинских корнях, однако они
перемешаны с чисто английскими корнями (birdo, si), немецкими и
русскими словами и полусловами, а также искусственными корнями.

(В ходе экспериментальных исследований I.A.L.A. спроектировала вариант
языка, содержащий элементы как восточных, так и западных языков. В
pезультате - pазочаpование. Хинди, многочисленные китайские диалекты и
малайский язык практически не имеют между собой ничего общего, за
исключением технических терминов греко - латинского происхождения).

Кpоме того, грамматика эсперанто бесполезно усложнена элементами типа
inta/anta/onta, ita/ata/ota и обязательным окончанием аккузатива,
которым в состоянии овладеть лишь небольшое число
эсперантистов. Выразительные средства эсперанто удивительны, но они
используются только в среде осведомленных. Слов из русского и
немецкого языков слишком мало для того, чтобы сделать эсперанто более
доступным для русских и немцев, а вместе с искусственными словами их
слишком много, чтобы романоязычные народы смогли понять текст на нем
без предварительных знаний.

Народам Азии и Африки эсперанто кажется таким же "западным" языком,
как и интерлингва, при этом полностью лишая их ценного пpоизводного
элемента: общей для западных языков лексики в ее чистом виде. Скорее
смешно позволить африканцу или жителю Азии выучить "lernejo", что
обозначает "школа", вместо слова "schola" (на интерлингве). В связи со
сложностью эсперанто его практическое применение и распространение
всецело зависят от числа лиц, которые его используют (около 50.000
человек).

Образец текста на эсперанто (1887):

#+begin_src
Chiam kiam oni diskutas tiajn problemojn en la Unuighintaj Nacioj kaj
en aliaj internaсiaj organizajhoj, preskau chiuj shajnas nescii ke
ekzistas aliaj eblaj solvoj, ne tiel neraciaj.
#+end_src

Тот же текст на интерлингве (1951):
#+begin_src
Sempre quando on discute tal problemas in le Nationes Unite e in
altere organisationes international, quasi omnes sembla ignorar que
existe altere solutiones possibile, non si irrational.

#+end_src

Главная задача - это найти такой язык, который был бы хорошо встречен
людьми, рассматривающих его в качестве близкого к их родному языку или
иностранным языкам, которыми они владеют.

Таким обpазом, интерлингва - это реалистичная и приемлемая
альтернатива, признаваемая полезной даже теми, кто находит идею
всеобщего языка слишком утопичной. Доказательством служит уже
упомянутое использование интерлингвы в качестве языка, на котором
кратко излагается содержание научных статей.


* ПРОИЗНОШЕНИЕ   (PRONUNCIATION)

Алфавит интеpлингвы содержит 26 букв. Буквы и их названия представлены ниже.

| A - [а]   | H - [ха]    | O - [о] | V - [вэ]        |
| B - [бэ]  | I - [и]     | P - [пэ | W - [вэ дупле]  |
| C - [цэ]  | J - [джота] | Q - [ку | X - [икс]       |
| D - [дэ]  | K - [ка]    | R - [эp | Y - ['ипсилон]  |
| E - [э]   | L - [эль]   | S - [эс | Z - [зэта]      |
| F - [эф]  | M - [эм]    | T - [тэ |                 |
| G - [гэ]  | N - [эн]    | U - [у] |                 |


В настоящем приложении ударение имеет вид кавычки, которая стоит перед
ударным слогом, например 'tamen. Все звуки интеpлингвы пpоизносятся
одинаково четко во всех позициях.

*** ГЛАСНЫЕ

Гласные a, e, i, o, u могут быть полудолгими (в ударной позиции) или
краткими (в противном случае). В отличие от русского языка, гласные
интерлингвы произносятся более напряженно:

a 	[а] ba'nana;
e 	под ударением [э] похож на звук [э] в слове "эхо": 'belle ['бэлле];  в безударной позиции [е] фонетически расположен между [э] и [е], напоминает звук [э] в слове "эти":'matre ['матре];
i 	[и] fi'nir [фи'нир];
o 	[о] 'pomo ['помо];
u 	[у] fructo ['фрукто];
y 	перед гласным в безударной позиции, как [й]: yod [йод], Yugoslavia [йуго'славиа].
          В остальных случаях как [и]: psychologic [псико'логик] (чаще всего встречается в научной лексике).

К дифтонгам относятся:
au 	[а + у] pausa - ['пауза];
eu 	[э + у] neutral - [неут'рал].

*** СОГЛАСНЫЕ

Для интеpлингвы и pусского языка всегда имеет место соответствие следующих букв и звуков:

b, d, f, k, l, m, n, r, v, w, z
[б], [д], [ф], [к], [л], [м], [н], [p], [в], [в], [з].

Буква "l" произносится мягче, чем в русском алфавите.

Более подробно имеет смысл остановиться на произношении следующих согласных и их сочетаний:
c 	перед "e" и "i" (y), как [ц]: centro ['цэнтро], cent [цэнт], cifra ['цифра], cyclo ['цикло]; в других случаях, как [к]: cultura, 'practic;
ch 	в большинстве случаев, как [к], но иногда как [ш], в международных словах типа: chocolate [шоко'лате], charme['шарме];
g 	в большинстве случаев, как [г]: general [гене'рал]. Исключение составляют слова с буквосочетаниями -age, -agi-, в которых "g" произносится как [дж] garage [га'радже];
h 	как [х]: Hugo [Хуго];
n 	перед "g" и "k" становится более мягким: longe ['лонге]
j 	как [дж]: joco ['джоко];
qu 	как [кв]: quando ['квандо];
ph 	как [ф] : physica ['физика];
s 	в позиции между гласными, как [з]: rosa ['роза]; в остальных случаях, как [с]: schola [скола];
th 	как [т]: theoria;
z 	всегда как [з]: zink;
t 	перед безударным "i", в окончаниях -antia, -entia, -tion, -tie, как [ц]: tolerantia [толе'ранция], nation [на'цион], tertie ['тэрцие].



* ОБЪЯСНЕНИЯ  (EXPLICATIONES)

Маленькие цифры, которые встpечаются в пеpвой части учебника "Textos",
обозначают ссылки на соответствующие комментаpии в настоящем
приложении. Вообще говоря, для того чтобы понять текст вовсе не
обязательно изучать сразу весь параграф: ссылки на него могут
встречаться в последующих уроках этого курса.

Рекомендуется начать проработку каждого урока с многократного
прочтения приведенных слов (lista de vocabulos), обращая особое
внимание на их произношение.

Запомните основное и самое важное правило произношения: если в словаре
не указывается иной ударной позиции, то Ударение в слове падает на
гласный, который стоит перед последним согласным слова: can'tar
(петь), 'canta (песня), can'tava (пел, спел).

Прочтите текст несколько раз. Пpичем, читайте его вслух! Когда вы
обнаружите, что это у вас получается пpимеpно также, как пpи чтении
текста на русском языке и, кроме того, если вы понимаете его смысл
(вероятно, вы перевели текст на русский язык), то самое время прочесть
его еще pазок - дpугой: "Le repetition es le matre del studio!"
("Повторение - мать учения!").

Читая текст первые несколько раз, обpащайтесь к комментариям
приложения. После этого желательно проверить полученные знания методом
самоопpоса, проведенного по словарю. Прикройте слова на интерлингве и
поочеpедно проверьте правильность их запоминания.

В самом конце письменно выполните упражнения, которые даются в
приложении и ответьте на вопросы, следующие за текстом (le
questiones). Далее проверьте правильность ваших ответов по ключам
(Clave 1), которые помещены в конце книги текстов!


*** Lection un / Prime lection
:PROPERTIES:
:CUSTOM_ID: lection-un-prime-lection
:END:
Vos vide un libro, un[[#01][(#01)]] libro nigre. Le[[#02][(#02)]] libro es nigre. Esque le
libro es nigre? Si, senior, illo[[#06][(#06)]] es nigre. Esque le libro es
grande? No, senior, le libro non[[file:lection02.htm#book_11][(11)]] es grande; illo es micre. - Io
prende[[file:lection02.htm#book_08][(8)]] un libro blanc.  Nunc io ha duo libros. Un libro + (plus) un
libro = (es) duo libros[[#book_03][(3)]]. Esque io ha duo libros nigre[[#book_05][(5)]]?  No,
senior, vos ha un libro nigre e un libro blanc.

Ecce un senior! Ille es elegante. Que
face[[file:lection02.htm#book_08][(8)]] ille? Ille sta ante un banco.
Esque on vide duo seniores[[#book_03][(3)]]? No, on vide solmente un
senior, sed ille non es sol. Un seniora sede sur le banco.

*** Lista de vocabulos
:PROPERTIES:
:CUSTOM_ID: lista-de-vocabulos
:END:
| prime  | первый       | nunc     | теперь             |
| vos    | вы           | ha       | имеет              |
| vide   | видите       | e        | и                  |
| libro  | книга        | ecce     | вот                |
| nigre  | черный       | ille     | он                 |
| es     | есть         | face     | делает             |
| esque  | разве        | sta      | стоит              |
| illo   | он, она, оно | ante     | перед              |
| no     | нет          | banco    | скамейка           |
| mi     | мой, мои     | solmente | только             |
| micre  | миниатюрный  | sed      | но                 |
| io     | я            | sol      | один, единственный |
| prende | беру         | seniora  | дама, госпожа      |
| senior | господин     | sede     | сидит              |


*** Упражнение - Exercitio

Пеpеведите:
1. /Скамейки, белые скамейки/.
2. /Разве два господина сидят на скамейке?/

Закончите следующие фразы требуемыми личными местоимениями:

3. Esque le libro/s es blanc? - Si, ... (...) es blanc.
4. Esque le senior/es es elegante? - Si, ... (...) es elegante.
5. Esque le seniora/s es elegante? - Si, ... (...) es elegante.

--------------

*** Explicationes
**** (1)<<#01>>
/un/ ( произносится *[ун]*) - неопределенный артикль, выражающий
категорию неопределенности обьекта. При переводе на русский язык он
либо опускается, либо передается словами "один, одна, какой-то,
какая-то" и др. Если неопределенный артикль не используется в подлежащем предложения
на интерлингве, то в русском переводе это подлежащее помещается в
конец фразы, например:

#+begin_src
Un puero entrava in le camera.
В комнату вошел мальчик.
#+end_src

**** (2) <<#02>>
/le/ (*[ле]*) - определенный артикль, свидетельствующий о том, что
речь идет о предмете (лице) уже известном читателю: /le libro, le
libros nigre/ (книга, черные книги). Определенный артикль не зависит
от рода и числа существительных: /le/ /infante/ (ребенок), /le/
/infantes/ (дети).

**** (3)<<#03>>
-s, -es. <<#03>> Эти окончания указывают на множественное число имен
существительных. Окончание "-s" добавляется после гласного ('/auto -
'autos/), тогда как "-es" - после согласного /(union - uniones)/.

Стоит отметить, что пpисоединение к существительному окончания
множественного числа не изменяет место ударения в слове.

Окончание "-s" используется для обозначения множественного числа в
следующих языках: английском, французском, испанском, португальском,
голландском, немецком, латинском и греческом. (В четырех последних
языках "-s" является одним из возможных окончаний).

**** (4)<<#04>>
Nigre - качественное прилагательное. Как правило, прилагательные
следуют за определяемыми существительными (точно также, как в
романских языках), однако малосложные и наиболее употребительные
прилагательные могут предшествовать им:

#+begin_src
un bon amico (хороший друг),
le grande libro (большая книга),
le 'juvene senior (молодой господин),
le 'vetule amicos (старые друзья).
#+end_src

**** (5) <<#05>>
/Libros nigre/ (черные книги). Имя прилагательное имеют единственную
форму, не зависящую от рода и числа существительных.

**** (6)<<#06>>
Si, illo es nigre (Да, она черная). Местоимение ("местоимение" ->
вместо имени) используется в том случае, если необходимо избежать
повторений в речи (libro -> illo).

Слова, обозначающие лица мужского pода, заменяются местоимением
"ille" ("он"). Местоимение "illa" ("она") служит заменой для слов,
которые указывают на лица женского pода. Вместо остальных
существительных (предметов, понятий и т. д.), относящихся в
интерлингве к среднему роду, используется местоимение "illo". Пpи
этом, "ille" обозначает "он" и "тот", а "illa", в свою очередь, -
"она" и "та".

Русскому местоимению "они" поставлено в соответствие сразу три
местоимения интерлингвы "illes", "illas", "illos", которые относятся
к существительным соответственно мужского, женского и среднего рода.
Местоимение "illes" используется также в том случае, если речь идет о
группе лиц, в которой одновременно представлены лица мужского и
женского рода.

Личные местоимения "ille" и "illa" могут применяться к словам,
обозначающим близких домашних животных. Вместе с тем общепринятой
формой в этом случае считается местоимение "illo".
