Lectiones un

*** Lection un / Prime lection
:PROPERTIES:
:CUSTOM_ID: lection-un-prime-lection
:END:
Vos vide un libro, un[[#01][(#01)]] libro nigre. Le[[#02][(#02)]] libro es nigre. Esque le
libro es nigre? Si, senior, illo[[#06][(#06)]] es nigre. Esque le libro es
grande? No, senior, le libro non[[file:lection02.htm#book_11][(11)]] es grande; illo es micre. - Io
prende[[file:lection02.htm#book_08][(8)]] un libro blanc.  Nunc io ha duo libros. Un libro + (plus) un
libro = (es) duo libros[[#book_03][(3)]]. Esque io ha duo libros nigre[[#book_05][(5)]]?  No,
senior, vos ha un libro nigre e un libro blanc.

Ecce un senior! Ille es elegante. Que
face[[file:lection02.htm#book_08][(8)]] ille? Ille sta ante un banco.
Esque on vide duo seniores[[#book_03][(3)]]? No, on vide solmente un
senior, sed ille non es sol. Un seniora sede sur le banco.

*** Lista de vocabulos
:PROPERTIES:
:CUSTOM_ID: lista-de-vocabulos
:END:
| prime  | первый       | nunc     | теперь             |
| vos    | вы           | ha       | имеет              |
| vide   | видите       | e        | и                  |
| libro  | книга        | ecce     | вот                |
| nigre  | черный       | ille     | он                 |
| es     | есть         | face     | делает             |
| esque  | разве        | sta      | стоит              |
| illo   | он, она, оно | ante     | перед              |
| no     | нет          | banco    | скамейка           |
| mi     | мой, мои     | solmente | только             |
| micre  | миниатюрный  | sed      | но                 |
| io     | я            | sol      | один, единственный |
| prende | беру         | seniora  | дама, госпожа      |
| senior | господин     | sede     | сидит              |


*** Упражнение - Exercitio

Пеpеведите:\\
1. /Скамейки, белые скамейки/.\\
2. /Разве два господина сидят на скамейке?/


--------------

*** Explicationes
**** <<#01>>
/un/ ( произносится *[ун]*) - неопределенный артикль, выражающий
категорию неопределенности обьекта. При переводе на русский язык он
либо опускается, либо передается словами "один, одна, какой-то,
какая-то" и др. Если неопределенный артикль не используется в подлежащем предложения
на интерлингве, то в русском переводе это подлежащее помещается в
конец фразы, например:

#+begin_src
Un puero entrava in le camera.
В комнату вошел мальчик.
#+end_src


****  <<#02>>
/le/ (*[ле]*) - определенный артикль, свидетельствующий о том, что
речь идет о предмете (лице) уже известном читателю: /le libro, le
libros nigre/ (книга, черные книги). Определенный артикль не зависит
от рода и числа существительных: /le/ /infante/ (ребенок), /le/
/infantes/ (дети).

**** <<#03>>
-s, -es. <<#03>> Эти окончания указывают на множественное число имен
существительных. Окончание "-s" добавляется после гласного ('/auto -
'autos/), тогда как "-es" - после согласного /(union - uniones)/.

Стоит отметить, что пpисоединение к существительному окончания
множественного числа не изменяет место ударения в слове.

Окончание "-s" используется для обозначения множественного числа в
следующих языках: английском, французском, испанском, португальском,
голландском, немецком, латинском и греческом. (В четырех последних
языках "-s" является одним из возможных окончаний).

**** <<#04>>
Nigre - качественное прилагательное. Как правило, прилагательные
следуют за определяемыми существительными (точно также, как в
романских языках), однако малосложные и наиболее употребительные
прилагательные могут предшествовать им:
#+begin_src
un bon amico (хороший друг),
le grande libro (большая книга),
le 'juvene senior (молодой господин),
le 'vetule amicos (старые друзья).
#+end_src


**** <<#05>>
/Libros nigre/ (черные книги). Имя прилагательное имеют единственную
форму, не зависящую от рода и числа существительных.

**** <<#06>>
6. Si, illo es nigre (Да, она черная). Местоимение ("местоимение" ->
   вместо имени) используется в том случае, если необходимо избежать
   повторений в речи (libro -> illo).\\
   Слова, обозначающие лица мужского pода, заменяются местоимением
   "ille" ("он"). Местоимение "illa" ("она") служит заменой для слов,
   которые указывают на лица женского pода. Вместо остальных
   существительных (предметов, понятий и т. д.), относящихся в
   интерлингве к среднему роду, используется местоимение "illo". Пpи
   этом, "ille" обозначает "он" и "тот", а "illa", в свою очередь, -
   "она" и "та".\\
   Русскому местоимению "они" поставлено в соответствие сразу три
   местоимения интерлингвы "illes", "illas", "illos", которые относятся
   к существительным соответственно мужского, женского и среднего рода.
   Местоимение "illes" используется также в том случае, если речь идет о
   группе лиц, в которой одновременно представлены лица мужского и
   женского рода.\\
   Личные местоимения "ille" и "illa" могут применяться к словам,
   обозначающим близких домашних животных. Вместе с тем общепринятой
   формой в этом случае считается местоимение "illo".

--------------

*Exercitio*

Закончите следующие фразы требуемыми личными местоимениями:\\
/3. Esque le libro/s es blanc? - Si, ... (...) es blanc.\\
4. Esque le senior/es es elegante? - Si, ... (...) es elegante.\\
5. Esque le seniora/s es elegante? - Si, ... (...) es elegante./
